import { Link } from 'react-router-dom'
import { BRAND, LOCK_TIERS } from '../brand'
import { Arrow } from '../components/Icons'
import { CaPill, Faq } from '../components/Ui'

export default function Home() {
  return (
    <>
      <section className="hero">
        <div className="wrap">
          <h1>
            Stake <span className="yellow">bStocks</span>
          </h1>

          <p className="lede">
            Stake bStocks on Binance Smart Chain. Every fee generated by our token is used to
            purchase bStocks which are distributed proportionally to users who stake their bStocks.
          </p>

          <CaPill />

          <div className="hero-cta">
            <Link className="btn btn-primary btn-lg" to="/stake">
              Stake bStocks
            </Link>
            <Link className="btn btn-ghost btn-lg" to="/tokens">
              Browse Tokens
            </Link>
          </div>
        </div>
      </section>

      <div className="wrap page">
        {/* ---------- how it works ---------- */}
        <section>
          <div className="section-head section-head-center">
            <h2>How it works</h2>
            <p>
              Trading fees are converted to purchase bStocks which are distributed proportionally to
              stakers.
            </p>
          </div>

          <div className="grid grid-3">
            <div className="step step-plain">
              <h3>Fees</h3>
              <p>
                Fees accumulate into reward pools on {BRAND.name} and are distributed proportionally
                to users staking on the platform.
              </p>
            </div>
            <div className="step step-plain">
              <h3>bStocks</h3>
              <p>
                Every fee generated by our token is used to purchase bStocks on Binance Smart Chain
                and distributed proportionally to users who stake their bStocks.
              </p>
            </div>
            <div className="step step-plain">
              <h3>Rewards</h3>
              <p>
                bStocks are split across everyone staking, in proportion to their share. Claim them
                whenever you like.
              </p>
            </div>
          </div>
        </section>

        {/* ---------- launch your own token ---------- */}
        <section className="section">
          <div className="section-head section-head-center">
            <h2>Launch a token with staking built in</h2>
            <p>
              Anyone can launch on {BRAND.name}. Pick a bStock to pair against and your holders can
              stake your token to earn that stock from the moment it exists.
            </p>
          </div>

          <div className="grid grid-3">
            <div className="step step-plain">
              <h3>Pick a stock</h3>
              <p>
                On {BRAND.launchpad} a token is launched against a quote asset. Choose a bStock and
                your token trades against it.
              </p>
            </div>
            <div className="step step-plain">
              <h3>Fees arrive as that stock</h3>
              <p>
                Because the pair is denominated in it, the fees your token generates are already in
                that stock.
              </p>
            </div>
            <div className="step step-plain">
              <h3>Holders stake and earn</h3>
              <p>Holders stake your token and receive the paired bStock in return.</p>
            </div>
          </div>

          <div className="card" style={{ marginTop: 18 }}>
            <div className="grid grid-lead" style={{ gap: 28, alignItems: 'center' }}>
              <div>
                <h3 style={{ fontSize: 20 }}>Why pair against a stock at all?</h3>
                <p className="muted" style={{ fontSize: 14.5, lineHeight: 1.75, marginTop: 12 }}>
                  A token paired against BNB pays its holders in BNB — one volatile asset rewarding
                  another. Paired against a bStock, the volatility stays where the upside is.
                </p>
                <Link className="btn btn-outline" to="/launch" style={{ marginTop: 18 }}>
                  Launch a token <Arrow />
                </Link>
              </div>
              <div className="pair-demo">
                <div className="pair-row">
                  <span className="pair-token">Your token</span>
                  <span className="pair-arrow">→</span>
                  <span className="badge badge-stock">NVDAB</span>
                </div>
                <div className="pair-note">trades against</div>
                <div className="pair-row">
                  <span className="pair-token">Trading fees</span>
                  <span className="pair-arrow">→</span>
                  <span className="badge badge-stock">NVDAB</span>
                </div>
                <div className="pair-note">paid to stakers</div>
              </div>
            </div>
          </div>
        </section>

        {/* ---------- lock durations ----------
            Durations only. The multiplier values are deliberately not published anywhere on the
            site; the yield calculator derives them. */}
        <section className="section">
          <div className="section-head section-head-center">
            <h2>Lock durations</h2>
            <p>
              Reward weight increases with longer lock durations, multipliers are calculated
              automatically by the yield calculator.
            </p>
          </div>
          <div className="mult-grid">
            {LOCK_TIERS.map((t) => (
              <div className={`mult mult-duration ${t.days === 30 ? 'on' : ''}`} key={t.days}>
                <div className="m mono">{t.days}</div>
                <div className="d">{t.days === 1 ? 'day' : 'days'}</div>
              </div>
            ))}
          </div>
        </section>

        {/* ---------- what a bStock is ---------- */}
        <section className="section">
          {/* No align-items override: grid items stretch by default, so both cards share the
              height of the taller one. */}
          <div className="grid grid-lead">
            <div className="card">
              <h2 style={{ fontSize: 24 }}>What are bStocks</h2>
              <p className="muted" style={{ marginTop: 12, fontSize: 14.5, lineHeight: 1.65 }}>
                A bStock is a BEP-20 token on {BRAND.chain} representing one real US share held with
                a regulated custodian, 1:1. It gives full economic exposure to the underlying price,
                dividends, corporate actions and trades 24/7.
              </p>
              <ul style={{ color: 'var(--text-2)', fontSize: 14.5, lineHeight: 1.9, paddingLeft: 20, marginTop: 14 }}>
                <li>Held in your own wallet, transferable like any BEP-20</li>
                <li>Tradeable on PancakeSwap and usable as DeFi collateral</li>
                <li>Fractional — rewards arrive as fractions of a share</li>
              </ul>
              <Link className="btn btn-outline" to="/bstocks" style={{ marginTop: 20 }}>
                Browse every stock <Arrow />
              </Link>
            </div>

            <div className="card">
              <h2 style={{ fontSize: 24 }}>Protocol Details</h2>
              <div className="summary" style={{ marginTop: 16 }}>
                <div className="summary-row">
                  <span className="k">Custody</span>
                  <span className="v" style={{ fontFamily: 'var(--font)' }}>
                    Your wallet
                  </span>
                </div>
                <div className="summary-row">
                  <span className="k">Early unlock</span>
                  <span className="v" style={{ fontFamily: 'var(--font)' }}>
                    Not permitted
                  </span>
                </div>
                <div className="summary-row">
                  <span className="k">Protocol cut</span>
                  <span className="v">{BRAND.protocolFeeBps / 100}%</span>
                </div>
                <div className="summary-row">
                  <span className="k">Listing fee</span>
                  <span className="v" style={{ fontFamily: 'var(--font)' }}>
                    None
                  </span>
                </div>
                <div className="summary-row">
                  <span className="k">Rewards</span>
                  <span className="v" style={{ fontFamily: 'var(--font)' }}>
                    Only what fees earn
                  </span>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ---------- FAQ ---------- */}
        <section className="section">
          <div className="section-head section-head-center">
            <h2>Questions</h2>
          </div>
          <Faq
            items={[
              {
                q: 'Where do the rewards actually come from?',
                a: `Trading fees, and nothing else. A token paired against a bStock generates fees denominated in that stock; those fees are claimed and split across everyone staking.`,
              },
              {
                q: 'Which stock do I get paid in?',
                a: 'Whichever bStock is staked or whichever bStock the token is paired against. A token paired with NVDAB pays NVDAB, a token paired with TSLAB pays TSLAB.',
              },
              {
                q: 'Can I unlock early?',
                a: 'No, the lock is enforced on chain. The multiplier only means something because the commitment is real. Rewards already credited stay claimable throughout, and your tokens return automatically when the lock expires.',
              },
              {
                q: 'How do I launch a token?',
                a: `Connect your wallet, give the token a name and a ticker, and choose the bStock you want it paired against. You sign the launch from your own wallet and stay the owner of the token, so ${BRAND.name} never takes custody of it or of your treasury. Staking opens on it the moment it exists, and listing is free.`,
              },
            ]}
          />
        </section>

        {/* ---------- CTA ---------- */}
        <section className="section">
          <div className="cta">
            <h2>Ready to earn real equity?</h2>
            <p>Connect a {BRAND.chain} wallet, stake, and let the fees do the rest.</p>
            <Link className="btn btn-lg btn-dark" to="/stake">
              Stake <Arrow />
            </Link>
          </div>
        </section>
      </div>
    </>
  )
}
